import QRCode from "qrcode";
import { canonical } from "@/config/site";

/**
 * Scannable QR code linking to a batch's verification page — the physical link
 * between the jar and its lab report (Dev Kit §08/§13).
 *
 * Rendered server-side as an inline SVG: no runtime JS, no external QR service,
 * and it works offline. The SVG is generated by us from a known URL, so
 * injecting it is safe.
 */
export async function BatchQr({
  batchNumber,
  size = 128,
  className,
}: {
  batchNumber: string;
  size?: number;
  className?: string;
}) {
  const url = canonical(`verify/${batchNumber}`);
  const svg = await QRCode.toString(url, {
    type: "svg",
    margin: 1,
    width: size,
    color: { dark: "#15284C", light: "#FFFFFF" },
    errorCorrectionLevel: "M",
  });

  return (
    <figure className={className}>
      <div
        className="inline-block rounded border border-navy/10 bg-white p-2"
        role="img"
        aria-label={`QR code linking to the lab report for batch ${batchNumber}`}
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      <figcaption className="mt-2 text-[11px] font-light leading-snug text-navy/50">
        Scan to verify batch
        <span className="block font-medium text-navy/70">{batchNumber}</span>
      </figcaption>
    </figure>
  );
}
